# Generated by Django 5.1.1 on 2024-09-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('github', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=255)),
                ('personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='resume.personaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('start_month', models.CharField(blank=True, max_length=10, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_month', models.CharField(blank=True, max_length=10, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('degree', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume.personaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.personaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('start_month', models.CharField(blank=True, max_length=10, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_month', models.CharField(blank=True, max_length=10, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='resume.personaldetail')),
            ],
        ),
    ]
