# Generated by Django 5.1.1 on 2024-09-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetail',
            old_name='github',
            new_name='website',
        ),
    ]
