# Generated by Django 5.1.1 on 2024-09-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_github_personaldetail_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_year',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
