# Generated by Django 5.1.1 on 2024-09-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_education_end_month_remove_education_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='linkedin',
        ),
    ]
