# Generated by Django 5.1.1 on 2024-09-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_personaldetail_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='website',
            field=models.CharField(default='https://in.linkedin.com', max_length=225),
        ),
    ]
