# Generated by Django 5.1.1 on 2024-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_personaldetail_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='website',
            field=models.CharField(blank=True, default='https://in.linkedin.com', max_length=225),
        ),
    ]
