# Generated by Django 5.1 on 2024-10-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_pdfupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PDFUpload',
        ),
    ]
