# Generated by Django 5.1 on 2024-10-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_uploadedfile_delete_pdfupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
